services:
  mysql:
    image: mysql:8.4
    container_name: spring-microservices-lab-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: microservice_section_7
      MYSQL_USER: spring
      MYSQL_PASSWORD: spring
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10

  postgres:
    image: postgres:17
    container_name: spring-microservices-lab-postgres
    environment:
      POSTGRES_DB: user_email_service
      POSTGRES_USER: spring
      POSTGRES_PASSWORD: spring
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U spring -d user_email_service"]
      interval: 10s
      timeout: 5s
      retries: 10

  rabbitmq:
    image: rabbitmq:4-management
    container_name: spring-microservices-lab-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  mysql_data:
  postgres_data:
  rabbitmq_data:
