spring:
  application:
    name: exchange-service-microsservice
  datasource:
    url: jdbc:mysql://localhost:3306/microservice_section_7
    username: spring
    password: spring
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    table: flyway_schema_history_exchange
    baseline-on-migrate: true
    baseline-version: 0
  jpa:
    hibernate:
      # Vou utilizar none para não criar as tabelas automaticamente, pois já tenho o script ddl.sql que cria as tabelas
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
    open-in-view: false
server:
  port: 8001
management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
