spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
            globalcors:
              add-to-simple-url-handler-mapping: true
              cors-configurations:
                '[/**]':
                  allowedOrigins:
                    - "*"
                  allowedMethods:
                    - GET
                    - POST
                    - PUT
                    - PATCH
                    - DELETE
                    - OPTIONS
                  allowedHeaders:
                    - "*"
            routes:
              - id: book-service
                uri: ${BOOK_SERVICE_URL:http://localhost:8100}
                predicates:
                  - Path=/book-service-microsservice/**
                filters:
                  - StripPrefix=1
              - id: book-service-short-path
                uri: ${BOOK_SERVICE_URL:http://localhost:8100}
                predicates:
                  - Path=/book-service/**
              - id: exchange-service
                uri: ${EXCHANGE_SERVICE_URL:http://localhost:8000}
                predicates:
                  - Path=/exchange-service-microsservice/**
                filters:
                  - StripPrefix=1
              - id: exchange-service-short-path
                uri: ${EXCHANGE_SERVICE_URL:http://localhost:8000}
                predicates:
                  - Path=/exchange-service/**
#          discovery:
#            locator:
#              enabled: true
#              lower-case-service-id: true
springdoc:
  swagger-ui:
    urls:
      - name: Book Service
        url: /book-service-microsservice/v3/api-docs
      - name: Exchange Service
        url: /exchange-service-microsservice/v3/api-docs
server:
  port: 8765
management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
