name: Microsservices Continuous Deployment with Github Actions

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v4
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

    - name: Set up  JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: '21'

    - name: Build Eureka Naming Server Docker Image
      run: |
        docker build --build-arg SERVICE_DIR=services/naming-server -t spring-microservices-lab-naming-server:latest -f Dockerfile .

    - name: Build API Gateway Docker Image
      run: |
        docker build --build-arg SERVICE_DIR=services/api-gateway -t spring-microservices-lab-api-gateway:latest -f Dockerfile .

    - name: Build Exchange Service Docker Image
      run: |
        docker build --build-arg SERVICE_DIR=services/exchange-service-microsservice -t spring-microservices-lab-exchange-service:latest -f Dockerfile .

    - name: Build Book Service Docker Image
      run: |
        docker build --build-arg SERVICE_DIR=services/book-service-microsservice -t spring-microservices-lab-book-service:latest -f Dockerfile .

    - name: Build Docker Compose Services
      run: docker compose build
